/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ik.ijse.Supermarket.view;

import ik.ijse.Supermarket.controller.CustomerController;
import ik.ijse.Supermarket.model.Customer;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author DilshanRajika
 */
public class AddCustomerForm extends javax.swing.JFrame {

    /**
     * Creates new form AddCustomerForm
     */
    public AddCustomerForm() {
        initComponents();
        loadCustTitle();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textcustid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textaddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        boxprovince = new javax.swing.JComboBox<>();
        textpostalcode = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        boxtitle = new javax.swing.JComboBox<>();
        SaveButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        textcity = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Add Customer Form");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 260, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CustomerID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 90, 30));

        textcustid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(textcustid, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 180, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Customer Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 140, 30));

        textname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(textname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 180, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Address");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 80, 30));

        textaddress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(textaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 180, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Province");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 90, 30));

        jPanel1.add(boxprovince, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 120, 30));

        textpostalcode.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(textpostalcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 120, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Postal Code");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 90, 30));

        jPanel1.add(boxtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 90, 30));

        SaveButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SaveButton.setText("Save");
        SaveButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SaveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 90, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 520, 10));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("City");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 80, 30));

        textcity.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(textcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 180, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ik/ijse/Supermarket/image/addcustomer.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 280));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
 
        try {
           if(textcustid.getText().length()>0&&textaddress.getText().length()>0&&textname.getText().length()>0){
             String custid=textcustid.getText();
             String title=boxtitle.getSelectedItem().toString();
             String custname=textname.getText();
             String custaddress=textaddress.getText();
             String city=textcity.getText();
             String province=boxprovince.getSelectedItem().toString();
             String postalcode=textpostalcode.getText();
             Customer customer=new Customer(custid,title,custname, custaddress, city, province, postalcode);
           boolean isadded= CustomerController.AddnewCustomer(customer);
           if(isadded){
           JOptionPane.showMessageDialog(null,"Customer Added Successfully");
           }else{
           JOptionPane.showMessageDialog(null,"Customer added fail!","",JOptionPane.WARNING_MESSAGE);
           }
           }else{
           
           }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }//GEN-LAST:event_SaveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCustomerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SaveButton;
    private javax.swing.JComboBox<String> boxprovince;
    private javax.swing.JComboBox<String> boxtitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField textaddress;
    private javax.swing.JTextField textcity;
    private javax.swing.JTextField textcustid;
    private javax.swing.JTextField textname;
    private javax.swing.JTextField textpostalcode;
    // End of variables declaration//GEN-END:variables

    private void loadCustTitle() {
        String []custtitle={"Miss","Mr","Ms"};
        for (int i = 0; i < custtitle.length; i++) {
           boxtitle.addItem(custtitle[i]); 
        }
        String[]province={"Northern", "North Western"," Western" ,"North Central" ,"Central"," Sabaragamuwa"," Eastern"," Uva"," Southern"};
        for (int i = 0; i < province.length; i++) {
           boxprovince.addItem(province[i]); 
        }
 
    }
}
