/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ik.ijse.Supermarket.view;


import ik.ijse.Supermarket.controller.ItemController;
import ik.ijse.Supermarket.model.Item;
import java.awt.event.ActionEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DilshanRajika
 */
public class SystemAdministratorForm extends javax.swing.JFrame {

    /**
     * Creates new form SystemAdministratorForm
     */
    public SystemAdministratorForm() {
        initComponents();
        LoadItem();
        LoadTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        DailyIncomeForm = new javax.swing.JButton();
        MonthlyIncomeForm = new javax.swing.JButton();
        LeastMoviableItem = new javax.swing.JButton();
        CustomerwiseIncome = new javax.swing.JButton();
        MostMoviableItem = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemtablelist = new javax.swing.JTable();
        itemcodetext = new javax.swing.JTextField();
        unitpricetext = new javax.swing.JTextField();
        descriptiontext = new javax.swing.JTextField();
        qtytext = new javax.swing.JTextField();
        packsizetext = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        AddButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lbldatetime = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 880, 10));

        jPanel3.setBackground(new java.awt.Color(51, 255, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DailyIncomeForm.setFont(new java.awt.Font("Thibus29STru", 0, 14)); // NOI18N
        DailyIncomeForm.setText("Daily Income");
        DailyIncomeForm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DailyIncomeForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DailyIncomeFormActionPerformed(evt);
            }
        });
        jPanel3.add(DailyIncomeForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 80, 176, 38));

        MonthlyIncomeForm.setFont(new java.awt.Font("Thibus29STru", 0, 14)); // NOI18N
        MonthlyIncomeForm.setText("Monthly Income");
        MonthlyIncomeForm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MonthlyIncomeForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonthlyIncomeFormActionPerformed(evt);
            }
        });
        jPanel3.add(MonthlyIncomeForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 124, 176, 38));

        LeastMoviableItem.setFont(new java.awt.Font("Thibus29STru", 0, 14)); // NOI18N
        LeastMoviableItem.setText("Least Moviable Item");
        LeastMoviableItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LeastMoviableItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeastMoviableItemActionPerformed(evt);
            }
        });
        jPanel3.add(LeastMoviableItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 168, 176, 38));

        CustomerwiseIncome.setFont(new java.awt.Font("Thibus29STru", 0, 14)); // NOI18N
        CustomerwiseIncome.setText("Customer wise Income");
        CustomerwiseIncome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CustomerwiseIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerwiseIncomeActionPerformed(evt);
            }
        });
        jPanel3.add(CustomerwiseIncome, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 256, 176, 38));

        MostMoviableItem.setFont(new java.awt.Font("Thibus29STru", 0, 14)); // NOI18N
        MostMoviableItem.setText("Most Moviable Item");
        MostMoviableItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MostMoviableItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostMoviableItemActionPerformed(evt);
            }
        });
        jPanel3.add(MostMoviableItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 212, 176, 38));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ik/ijse/Supermarket/image/sidebar.png"))); // NOI18N
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -70, 180, 480));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 180, 410));

        itemtablelist.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        itemtablelist.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        itemtablelist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ItemCode", "Description", "PackSize", "UnitPrice", "QtyOnHand"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        itemtablelist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemtablelistMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(itemtablelist);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 670, 150));

        itemcodetext.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        itemcodetext.setForeground(new java.awt.Color(0, 51, 255));
        jPanel1.add(itemcodetext, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 140, 30));

        unitpricetext.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        unitpricetext.setForeground(new java.awt.Color(0, 51, 255));
        jPanel1.add(unitpricetext, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 140, 30));

        descriptiontext.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        descriptiontext.setForeground(new java.awt.Color(0, 51, 255));
        jPanel1.add(descriptiontext, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 140, 30));

        qtytext.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        qtytext.setForeground(new java.awt.Color(0, 51, 255));
        jPanel1.add(qtytext, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 140, 30));

        packsizetext.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        packsizetext.setForeground(new java.awt.Color(0, 51, 255));
        jPanel1.add(packsizetext, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 260, 140, 30));

        jLabel2.setFont(new java.awt.Font("Thibus29STru", 1, 14)); // NOI18N
        jLabel2.setText("Pack Size");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 260, 90, 30));

        jLabel3.setFont(new java.awt.Font("Thibus29STru", 1, 14)); // NOI18N
        jLabel3.setText("QtyOnHand");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 90, 30));

        jLabel4.setFont(new java.awt.Font("Thibus29STru", 1, 14)); // NOI18N
        jLabel4.setText("Description");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 90, 30));

        jLabel5.setFont(new java.awt.Font("Thibus29STru", 1, 14)); // NOI18N
        jLabel5.setText("Item Code");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 90, 30));

        jLabel6.setFont(new java.awt.Font("Thibus29STru", 1, 14)); // NOI18N
        jLabel6.setText("Unit Price");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 90, 30));

        AddButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AddButton.setText("Add ");
        AddButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        AddButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, 110, 30));

        UpdateButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        UpdateButton.setText("Update");
        UpdateButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        UpdateButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });
        jPanel1.add(UpdateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, 110, 30));

        DeleteButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DeleteButton.setText("Delete");
        DeleteButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        DeleteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });
        jPanel1.add(DeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 420, 110, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("System Administrator Form ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 540, 60));

        lbldatetime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbldatetime.setForeground(new java.awt.Color(204, 255, 204));
        jPanel1.add(lbldatetime, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 190, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ik/ijse/Supermarket/image/administrator.png"))); // NOI18N
        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemtablelistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemtablelistMouseClicked
     DefaultTableModel dtm=(DefaultTableModel) itemtablelist.getModel();
        int selectrow=itemtablelist.getSelectedRow();
        itemcodetext.setText(itemtablelist.getValueAt(selectrow,0).toString());
        descriptiontext.setText(itemtablelist.getValueAt(selectrow,1).toString());
        packsizetext.setText(itemtablelist.getValueAt(selectrow,2).toString());
        unitpricetext.setText(itemtablelist.getValueAt(selectrow,3).toString());
        qtytext.setText(itemtablelist.getValueAt(selectrow,4).toString());
    }//GEN-LAST:event_itemtablelistMouseClicked

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
       String itemcode=itemcodetext.getText();
       String description=descriptiontext.getText();
       String packsize=packsizetext.getText();
       double unitprice=Double.parseDouble(unitpricetext.getText());
       int qtyonhand=Integer.parseInt(qtytext.getText());
        Item item=new Item(itemcode, description, packsize, unitprice, qtyonhand);
        try {
           boolean isadded= ItemController.addItem(item);
           if(isadded){
           JOptionPane.showMessageDialog(null,"Item added Successfully!");
           }else{
           JOptionPane.showMessageDialog(null,"Item Added is Fail!","",JOptionPane.WARNING_MESSAGE);
           }
        } catch (ClassNotFoundException | SQLException ex) {
        JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_AddButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        String itemcode=itemcodetext.getText();
       String description=descriptiontext.getText();
       String packsize=packsizetext.getText();
       double unitprice=Double.parseDouble(unitpricetext.getText());
       int qtyonhand=Integer.parseInt(qtytext.getText());
        Item item=new Item(itemcode, description, packsize, unitprice, qtyonhand);
        try {
            boolean isupdated=ItemController.UpdateItem(item);
              if(isupdated){
           JOptionPane.showMessageDialog(null,"Item Update Successfully!");
           }else{
           JOptionPane.showMessageDialog(null,"Item Update is Fail!","",JOptionPane.WARNING_MESSAGE);
           }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
      String itemcode=itemcodetext.getText();
        try {
            boolean isdeleted=ItemController.DeleteItem(itemcode);
            if(isdeleted){
            JOptionPane.showMessageDialog(null,"Item Delete Successfully!");
            }else{
            JOptionPane.showMessageDialog(null,"Item Delete Fail!","",JOptionPane.WARNING_MESSAGE);
            }
        } catch (ClassNotFoundException | SQLException ex) {
           JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void MostMoviableItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostMoviableItemActionPerformed
        new MostMoviableItemForm().setVisible(true);
    }//GEN-LAST:event_MostMoviableItemActionPerformed

    private void CustomerwiseIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerwiseIncomeActionPerformed
        new CustomerIncomeForm().setVisible(true);
    }//GEN-LAST:event_CustomerwiseIncomeActionPerformed

    private void LeastMoviableItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeastMoviableItemActionPerformed
        new LeastMoviableItemForm().setVisible(true);
    }//GEN-LAST:event_LeastMoviableItemActionPerformed

    private void MonthlyIncomeFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonthlyIncomeFormActionPerformed
        new MonthlyIncomeForm().setVisible(true);
    }//GEN-LAST:event_MonthlyIncomeFormActionPerformed

    private void DailyIncomeFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DailyIncomeFormActionPerformed
        new DailyIncomeForm().setVisible(true);
    }//GEN-LAST:event_DailyIncomeFormActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SystemAdministratorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SystemAdministratorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SystemAdministratorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SystemAdministratorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SystemAdministratorForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton CustomerwiseIncome;
    private javax.swing.JButton DailyIncomeForm;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton LeastMoviableItem;
    private javax.swing.JButton MonthlyIncomeForm;
    private javax.swing.JButton MostMoviableItem;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JTextField descriptiontext;
    private javax.swing.JTextField itemcodetext;
    private javax.swing.JTable itemtablelist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbldatetime;
    private javax.swing.JTextField packsizetext;
    private javax.swing.JTextField qtytext;
    private javax.swing.JTextField unitpricetext;
    // End of variables declaration//GEN-END:variables

    private void LoadItem() {
    try {
            DefaultTableModel dtm=(DefaultTableModel)itemtablelist.getModel();
            ArrayList<Item> itemlist= ItemController.LoadItem();
           for(Item item:itemlist){
                Object rowdata[]={item.getItemCode(),item.getDescription(),item.getPackSize(),item.getUnitPrice(),item.getQtyOnHand()};
                dtm.addRow(rowdata);
           }
        } catch (ClassNotFoundException | SQLException ex) {
            String massage=ex.getMessage();
            JOptionPane.showMessageDialog(null, massage);
        }
    }

    private void LoadTime() {
new Timer(0, (ActionEvent e) -> {
   Date date=new Date();
        SimpleDateFormat stf=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
         String curdate=stf.format(date);
         lbldatetime.setText(curdate);
}).start();
    




    }
}
